openvinotoolkit/training_extensions

tensorflow_toolkit/ssd_detector/README.md
**Before submitting a pull request**, please make sure the following is done:
1. You have merged in the latest changes from `develop`.
2. Resolved any conflicts that may have happened from that merge.
3. Ensure that you have run all tests and linting locally.
=> fixed url for ssd detector model

pytorch_toolkit/object_detection/README_face_detection.md, pytorch_toolkit/object_detection/init_venv.sh, pytorch_toolkit/object_detection/prepare_mmdet.sh
Instruction contains description of taining/val scripts and related tools.
=> Add instructions for face detection

pytorch_toolkit/instance_segmentation/OpenVINO.md, pytorch_toolkit/instance_segmentation/README.md, pytorch_toolkit/instance_segmentation/segmentoly/extensions/deformable_conv/deform_conv_kernel.cu, pytorch_toolkit/instance_segmentation/segmentoly/extensions/deformable_conv/deform_conv_kernel.h, pytorch_toolkit/instance_segmentation/segmentoly/extensions/extensions.cpp, pytorch_toolkit/instance_segmentation/segmentoly/rcnn/deformable_conv.py, pytorch_toolkit/instance_segmentation/segmentoly/rcnn/model_zoo/panet_mask_rcnn_base.py, pytorch_toolkit/instance_segmentation/segmentoly/rcnn/model_zoo/resnet_panet_mask_rcnn.py, pytorch_toolkit/instance_segmentation/segmentoly/rcnn/panet.py, pytorch_toolkit/instance_segmentation/setup.py, pytorch_toolkit/instance_segmentation/tools/train.py
@AlexanderDokuchaev @snosov1 @druzhkov-paul, please take a look.
Here are two models: `0010`, `0083` in trainable format and also deformable convolutions.
=> Add code for training instance segmentation models 0010 and 0083 from OpenVINO Open Model Zoo

pytorch_toolkit/human_pose_estimation/datasets/lip.py, pytorch_toolkit/human_pose_estimation/requirements.txt
Fixed numpy version in requirements, removed double augmentation. Thanks @AnastasiaaSenina.
=> Fixed requirements file

pytorch_toolkit/super_resolution/.gitignore, pytorch_toolkit/super_resolution/README.md, pytorch_toolkit/super_resolution/configs/smallmodel_scale3.yaml, pytorch_toolkit/super_resolution/configs/smallmodel_scale4.yaml, pytorch_toolkit/super_resolution/sr/common.py, pytorch_toolkit/super_resolution/tools/export.py, pytorch_toolkit/super_resolution/tools/infer.py, pytorch_toolkit/super_resolution/tools/infer_ie.py, pytorch_toolkit/super_resolution/tools/test.py, pytorch_toolkit/super_resolution/tools/train.py
- Add config files https://github.com/opencv/openvino_training_extensions/issues/128
- Export to IR with some parameters as model in OMZ
=> Add config files for super-resolution models

pytorch_toolkit/instance_segmentation/segmentoly/data/transforms.py
**Before submitting a pull request**, please make sure the following is done:
1. You have merged in the latest changes from `develop`.
2. Resolved any conflicts that may have happened from that merge.
3. Ensure that you have run all tests and linting locally.
=> fix augmentation transform update

README.md, tensorflow_toolkit/README.md
https://github.com/opencv/openvino_training_extensions/issues/133
=> Update list of models in readme files

tensorflow_toolkit/image_retrieval/tools/train.py
hi
i try to  retrain image_retrueval, but there are some bugs. i am sure the weight is right.
Traceback (most recent call last):
File "tools/train.py", line 259, in 
main()
File "tools/train.py", line 168, in main
assert not args.model_weights
AssertionError
W0821 15:21:01.873234 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer
W0821 15:21:01.873397 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer.iter
W0821 15:21:01.873442 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer.beta_1
W0821 15:21:01.873475 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer.beta_2
W0821 15:21:01.873506 140256564483840 util.py:244] Unresolved object in checkpoint: (root).optimizer.decay
W0821 …
=> Fix bug for load weights

tensorflow_toolkit/image_retrieval/data/queries/queries.txt
@Ilya-Krylov  take a look please, looks like you made a typo in the file name for queries annotation
@AlexanderDokuchaev, please review my patch
=> fix typo in file name

pytorch_toolkit/object_detection/person_vehicle_bike_detection.md
https://github.com/opencv/openvino_training_extensions/issues/185
=> Fix paths for Person Vehicle Bike Detector

pytorch_toolkit/human_pose_estimation/README.md, pytorch_toolkit/human_pose_estimation/README_single.md, pytorch_toolkit/human_pose_estimation/datasets/coco_single.py, pytorch_toolkit/human_pose_estimation/datasets/lip.py, pytorch_toolkit/human_pose_estimation/datasets/transformations.py, pytorch_toolkit/human_pose_estimation/init_venv.sh, pytorch_toolkit/human_pose_estimation/modules/load_state.py, pytorch_toolkit/human_pose_estimation/modules/loss.py, pytorch_toolkit/human_pose_estimation/requirements.txt, pytorch_toolkit/human_pose_estimation/scripts/convert_to_onnx.py, pytorch_toolkit/human_pose_estimation/val_single.py
https://github.com/opencv/openvino_training_extensions/issues/233
https://github.com/opencv/openvino_training_extensions/issues/232
=> Fix training single-human-pose-estimation model on LIP dataset

pytorch_toolkit/nncf/examples/object_detection/main.py
=> Fix object detection best checkpoint saving

pytorch_toolkit/nncf/examples/common/utils.py
Quantization config has no 'params'.
=> Fix the name of log dir in NNCF

pytorch_toolkit/person_reidentification/config/default_config.py, pytorch_toolkit/person_reidentification/engine/builder.py, pytorch_toolkit/person_reidentification/engine/engine.py
=> Add flip eval to the reid training code

pytorch_toolkit/nncf/README.md
=> Fix NNCF documentation

pytorch_toolkit/nncf/README.md
=> Minor correction in README for nncf

pytorch_toolkit/object_detection/model_templates/custom-detection/mobilenet_v2-2s_ssd-256x256/template.yaml, pytorch_toolkit/object_detection/model_templates/custom-detection/mobilenet_v2-2s_ssd-384x384/template.yaml, pytorch_toolkit/object_detection/model_templates/custom-detection/mobilenet_v2-2s_ssd-512x512/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0200/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0202/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0204/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0205/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0206/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0207/template.yaml, pytorch_toolkit/object_detection/model_templates/horizontal-text-detection/horizontal-text-detection-0001/template.yaml, pytorch_toolkit/object_detection/model_templates/person-detection/person-detection-0200/template.yaml, pytorch_toolkit/object_detection/model_templates/person-detection/person-detection-0201/template.yaml, pytorch_toolkit/object_detection/model_templates/person-detection/person-detection-0202/template.yaml, pytorch_toolkit/object_detection/model_templates/person-vehicle-bike-detection/person-vehicle-bike-detection-2000/template.yaml, pytorch_toolkit/object_detection/model_templates/person-vehicle-bike-detection/person-vehicle-bike-detection-2001/template.yaml, pytorch_toolkit/object_detection/model_templates/person-vehicle-bike-detection/person-vehicle-bike-detection-2002/template.yaml, pytorch_toolkit/object_detection/model_templates/vehicle-detection/vehicle-detection-0200/template.yaml, pytorch_toolkit/object_detection/model_templates/vehicle-detection/vehicle-detection-0201/template.yaml, pytorch_toolkit/object_detection/model_templates/vehicle-detection/vehicle-detection-0202/template.yaml, pytorch_toolkit/object_detection/oteod/oteod/args_conversion.py, pytorch_toolkit/object_detection/oteod/oteod/training/common.py, pytorch_toolkit/ote/ote/api.py
Related to https://github.com/openvinotoolkit/mmdetection/pull/72
=> tensorboard dir

pytorch_toolkit/object_detection/model_templates/custom-detection/mobilenet_v2-2s_ssd-256x256/template.yaml, pytorch_toolkit/object_detection/model_templates/custom-detection/mobilenet_v2-2s_ssd-384x384/template.yaml, pytorch_toolkit/object_detection/model_templates/custom-detection/mobilenet_v2-2s_ssd-512x512/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0200/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0202/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0204/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0205/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0206/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0207/template.yaml, pytorch_toolkit/object_detection/model_templates/horizontal-text-detection/horizontal-text-detection-0001/template.yaml, pytorch_toolkit/object_detection/model_templates/person-detection/person-detection-0200/template.yaml, pytorch_toolkit/object_detection/model_templates/person-detection/person-detection-0201/template.yaml, pytorch_toolkit/object_detection/model_templates/person-detection/person-detection-0202/template.yaml, pytorch_toolkit/object_detection/model_templates/person-vehicle-bike-detection/person-vehicle-bike-detection-2000/template.yaml, pytorch_toolkit/object_detection/model_templates/person-vehicle-bike-detection/person-vehicle-bike-detection-2001/template.yaml, pytorch_toolkit/object_detection/model_templates/person-vehicle-bike-detection/person-vehicle-bike-detection-2002/template.yaml, pytorch_toolkit/object_detection/model_templates/vehicle-detection/vehicle-detection-0200/template.yaml, pytorch_toolkit/object_detection/model_templates/vehicle-detection/vehicle-detection-0201/template.yaml, pytorch_toolkit/object_detection/model_templates/vehicle-detection/vehicle-detection-0202/template.yaml
Updating OTEDetection framework version to 2.1.1 in order to conform with SemVer versioning.
=> Change OTEDetection framework version to 2.1.1

pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0205/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0206/template.yaml, pytorch_toolkit/object_detection/model_templates/horizontal-text-detection/horizontal-text-detection-0001/template.yaml, pytorch_toolkit/tools/instantiate_template.py
Removed CPU target since SigmoidFocalLoss is not implemented for CPU
=> Remove cpu from some templates

pytorch_toolkit/object_detection/model_templates/vehicle-detection/vehicle-detection-0203/template.yaml, pytorch_toolkit/object_detection/model_templates/vehicle-detection/vehicle-detection-0204/template.yaml, pytorch_toolkit/ote/readme.md
Updating OTEDetection version in new vehicle detection templates, in order to maintain consistency with other models
=> Update otedetection version in vehicle detection

pytorch_toolkit/question_answering/requirements.txt
fix transformers version. the new one (4.0) is not supported by pack code
=> question_answering: fix transformers version.

pytorch_toolkit/formula_recognition/im2latex/models/im2latex_model.py, pytorch_toolkit/formula_recognition/im2latex/models/text_recognition_heads/attention_based.py, pytorch_toolkit/formula_recognition/requirements.txt
Adds positional encodings to formula recognition training code like in transformer architecture. Positional encodings realization from https://github.com/tatp22/multidim-positional-encoding
PR also adds ability to disable trainable initial hidden state for every row in RNN decoder.
=> positional encodings in formula recognition & optional initial trainable hidden state

pytorch_toolkit/object_detection/model_templates/custom-detection/mobilenet_v2-2s_ssd-256x256/template.yaml, pytorch_toolkit/object_detection/model_templates/custom-detection/mobilenet_v2-2s_ssd-384x384/template.yaml, pytorch_toolkit/object_detection/model_templates/custom-detection/mobilenet_v2-2s_ssd-512x512/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0200/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0202/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0204/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0205/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0206/template.yaml, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0207/template.yaml, pytorch_toolkit/object_detection/model_templates/horizontal-text-detection/horizontal-text-detection-0001/template.yaml, pytorch_toolkit/object_detection/model_templates/person-detection/person-detection-0200/template.yaml, pytorch_toolkit/object_detection/model_templates/person-detection/person-detection-0201/template.yaml, pytorch_toolkit/object_detection/model_templates/person-detection/person-detection-0202/template.yaml, pytorch_toolkit/object_detection/model_templates/person-vehicle-bike-detection/person-vehicle-bike-detection-2000/template.yaml, pytorch_toolkit/object_detection/model_templates/person-vehicle-bike-detection/person-vehicle-bike-detection-2001/template.yaml, pytorch_toolkit/object_detection/model_templates/person-vehicle-bike-detection/person-vehicle-bike-detection-2002/template.yaml, pytorch_toolkit/object_detection/model_templates/vehicle-detection/vehicle-detection-0200/template.yaml, pytorch_toolkit/object_detection/model_templates/vehicle-detection/vehicle-detection-0201/template.yaml, pytorch_toolkit/object_detection/model_templates/vehicle-detection/vehicle-detection-0202/template.yaml, pytorch_toolkit/object_detection/model_templates/vehicle-detection/vehicle-detection-0203/template.yaml, pytorch_toolkit/object_detection/model_templates/vehicle-detection/vehicle-detection-0204/template.yaml
=> Classes updates in templates

pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0200/compression_config.json, pytorch_toolkit/object_detection/model_templates/face-detection/face-detection-0200/template.yaml, pytorch_toolkit/object_detection/tests/common/test_case.py, pytorch_toolkit/object_detection/tests/nncf_tests_face_detection.py, pytorch_toolkit/ote/ote/api.py, pytorch_toolkit/ote/ote/modules/arg_converters/base.py, pytorch_toolkit/ote/ote/modules/compression/__init__.py, pytorch_toolkit/ote/ote/modules/compression/nncf_config_generator.py, pytorch_toolkit/ote/ote/modules/compression/nncf_config_transformer.py, pytorch_toolkit/ote/ote/modules/exporters/mmdetection.py, pytorch_toolkit/ote/ote/tests/test_case.py, pytorch_toolkit/ote/tools/compress.py, pytorch_toolkit/ote/tools/eval.py, pytorch_toolkit/ote/tools/export.py, pytorch_toolkit/ote/tools/train.py
* Make NNCF configuration in template files be compliant with the external specs
* Add possibility to turn on NNCF compression flags from command line arguments of ote tools
=> Change NNCF part of templates

pytorch_toolkit/action_recognition_2/model_templates/gesture-recognition/README.md, pytorch_toolkit/instance_segmentation_2/model_templates/coco-instance-segmentation/readme.md, pytorch_toolkit/object_detection/model_templates/custom-detection/readme.md, pytorch_toolkit/object_detection/model_templates/face-detection/readme.md, pytorch_toolkit/object_detection/model_templates/horizontal-text-detection/readme.md, pytorch_toolkit/object_detection/model_templates/person-detection/readme.md, pytorch_toolkit/object_detection/model_templates/person-vehicle-bike-detection/readme.md, pytorch_toolkit/object_detection/model_templates/vehicle-detection/readme.md, pytorch_toolkit/text_spotting_2/model_templates/alphanumeric-text-spotting/readme.md
Updated documentation correspondingly to the current folder structure. Also added information about venv activation, though it should be discussed if it is really needed.
Changed python3 to python since this would be executed inside venv anyway.
Added new argument `--root` to the doc since it is required in `create_dataset.py` script
=> Fixes in horizontal_text_detection documentation

pytorch_toolkit/tests/run_model_templates_tests.sh
This script will allow to switch on CI between python
scripts run_model_templates_tests.py and run_model_templates_tests2.py
and/or adding command line parameters to these scripts.
=> Add script run_model_templates_tests.sh for CI

pytorch_toolkit/image_classification/model_templates/custom-classification/mobilenet_v2_w1/modules.yaml, pytorch_toolkit/image_classification/model_templates/custom-classification/mobilenet_v2_w1/template.yaml, pytorch_toolkit/ote/ote/modules/arg_converters/reid.py, pytorch_toolkit/ote/ote/modules/arg_parsers/__init__.py, pytorch_toolkit/ote/ote/modules/arg_parsers/reid.py, pytorch_toolkit/ote/ote/modules/trainers/reid.py
Also deep-object-reid was updated with classes checking features.
=> Add classes parameter to classification

pytorch_toolkit/object_reidentification/face_recognition/configs/face-reidentification-retail-0095.yaml, pytorch_toolkit/object_reidentification/person_reidentification/configs/person-reidentification-retail-0248.yaml, pytorch_toolkit/object_reidentification/person_reidentification/configs/person-reidentification-retail-0265.yaml, pytorch_toolkit/object_reidentification/person_reidentification/configs/person-reidentification-retail-0267.yaml, pytorch_toolkit/object_reidentification/person_reidentification/configs/person-reidentification-retail-0270.yaml
=> Fix reid configs and feature extractor

models/action_recognition/model_templates/custom-action-recognition/s3d-rgb-mobilenet-v3/model.py, models/action_recognition/tests/common/action_recognition_test_case.py, models/action_recognition/tests/export_tests_custom_recognition.py, models/action_recognition/tests/train_tests_custom_recognition.py, pytorch_toolkit/tests/run_model_templates_tests.sh
Fixed tests and config for the custom-action-recognition model template.
=> Custom Action Recognition fixes

models/object_detection/model_templates/horizontal-text-detection/tools/draw_recall_graph.py
Fixed imports and optimized its number. Changed script for more convenient histogram drawing and removed code that became irrelevant.
=> Fix imports in visualize_text_detection

models/object_detection/model_templates/custom-object-detection/mobilenet_v2-2s_ssd-256x256/compression_config.json, models/object_detection/model_templates/custom-object-detection/mobilenet_v2-2s_ssd-384x384/compression_config.json, models/object_detection/model_templates/custom-object-detection/mobilenet_v2-2s_ssd-512x512/compression_config.json, models/object_detection/model_templates/face-detection/face-detection-0206/compression_config.json, models/object_detection/model_templates/horizontal-text-detection/horizontal-text-detection-0001/compression_config.json, models/object_detection/model_templates/person-detection/person-detection-0203/compression_config.json
Add compression configs for custom-object-detection, face-detection-0206, horizontal-text-detection,
=> Add compression configs for new models

models/object_detection/model_templates/face-detection/face-detection-0200/compression_config.json, models/object_detection/model_templates/face-detection/face-detection-0202/compression_config.json, models/object_detection/model_templates/face-detection/face-detection-0204/compression_config.json, models/object_detection/model_templates/face-detection/face-detection-0205/compression_config.json, models/object_detection/model_templates/face-detection/face-detection-0207/compression_config.json, models/object_detection/model_templates/person-detection/person-detection-0200/compression_config.json, models/object_detection/model_templates/person-detection/person-detection-0201/compression_config.json, models/object_detection/model_templates/person-detection/person-detection-0202/compression_config.json, models/object_detection/model_templates/person-vehicle-bike-detection/person-vehicle-bike-detection-2000/compression_config.json, models/object_detection/model_templates/person-vehicle-bike-detection/person-vehicle-bike-detection-2001/compression_config.json, models/object_detection/model_templates/person-vehicle-bike-detection/person-vehicle-bike-detection-2002/compression_config.json, models/object_detection/model_templates/vehicle-detection/vehicle-detection-0200/compression_config.json, models/object_detection/model_templates/vehicle-detection/vehicle-detection-0201/compression_config.json, models/object_detection/model_templates/vehicle-detection/vehicle-detection-0202/compression_config.json
Add lr_configs and change names of NNCF initialization parameters
=> Update compression configs

models/instance_segmentation/model_templates/coco-instance-segmentation/instance-segmentation-0002/compression_config.json, models/instance_segmentation/model_templates/coco-instance-segmentation/instance-segmentation-0228/compression_config.json, models/instance_segmentation/model_templates/coco-instance-segmentation/instance-segmentation-0904/compression_config.json, models/instance_segmentation/model_templates/coco-instance-segmentation/instance-segmentation-0912/compression_config.json, models/object_detection/model_templates/face-detection/face-detection-0206/compression_config.json
=> Add NNCF configs for instance-segmentation models

misc/pytorch_toolkit/text_recognition/README.md, misc/pytorch_toolkit/text_recognition/requirements.txt, misc/pytorch_toolkit/text_recognition/text_recognition/datasets/dataset.py, misc/pytorch_toolkit/text_recognition/text_recognition/utils/trainer.py
Add support of text recognition datasets in LMDB format.
Also do not concatenate validation datasets, compute separate metric over every dataset and return weighted average.
=> support lmdb text rec datasets and

.gitmodules, models/instance_segmentation/init_venv.sh, models/object_detection/init_venv.sh
Now the installation of NNCF should be done using pip -- probably, using
the command
pip3 install -e git+http://github.com/openvinotoolkit/nncf@<commit_hash>#egg=nncf
=> Remove nncf submodule

tests/accuracy_validation/test_accuracy_validation.py
Freeze version scikit-image to 0.18.1, to avoid AC install error.
Changed venv for AC to Python 3.7 (because of Ubuntu 18 in docker)
=> Added sci-kit pre-install

tests/run_model_templates_tests.py
Also add possibility to save the filtered list of tests to a file.
=> Add to run_model_templates_tests.py possibility to load test ids from file

misc/pytorch_toolkit/text_recognition/README.md
* Fix subsection
* Add link to the publication & name for the model (for easier search)
=> minor updates to the readme for the text recognition

ote_cli/ote_cli/datasets/__init__.py, ote_cli/ote_cli/datasets/object_detection/dataset.py, ote_cli/ote_cli/datasets/semantic_segmentation/dataset.py, ote_cli/ote_cli/tools/export.py
This PR adds semantic segmentation dataset support for OTE CLI and updates submodules to their recent state.
=> [OTE CLI] Semantic Segmentation dataset

external/anomaly/ote/callbacks/inference.py
Computes the anomaly heatmaps in the inference callback and adds it to the dataset item as a metadata.
=> add anomaly heatmap to dataset item as metadata

external/anomaly/anomaly_classification/openvino.py, external/anomaly/anomaly_classification/task.py, external/anomaly/ote_anomalib/callbacks/inference.py, external/anomaly/ote_anomalib/config/config.py, external/anomaly/ote_anomalib/data/data.py, external/anomaly/setup.py, external/anomaly/tests/helpers/dataset.py, external/anomaly/tests/helpers/train.py, external/anomaly/tests/test_ote_anomaly_classification.py
- It builds on top of changes from https://github.com/openvinotoolkit/training_extensions/pull/689
=> Fix OpenVINO thresholding

external/anomaly/anomaly_classification/openvino.py, external/anomaly/ote_anomalib/callbacks/inference.py, external/anomaly/ote_anomalib/config/config.py, external/anomaly/ote_anomalib/data/data.py, external/anomaly/setup.py, external/anomaly/tests/helpers/dataset.py, external/anomaly/tests/helpers/train.py, external/anomaly/tests/test_ote_anomaly_classification.py
=> Address cancel training + isort

ote_cli/notebooks/train.ipynb
Changelog:
- Removed Gen1 and Gen2 templates.
- Updated init_venv to support different SDK location.
- Fix some tests.
Build 18890 ✔️
=> [Detection] Remove old templates

external/anomaly/ote_anomalib/data/data.py
Adds log messages that summarize the dataset received from OTE by listing the total number, number of normal examples, and number of anomalous examples in the training, validation and test subsets.
=> Anomaly: logging summary of received OTE dataset

.gitignore, ote_sdk/ote_sdk/tests/entities/dummy_config.yaml, ote_sdk/ote_sdk/tests/entities/dummy_template.yaml, ote_sdk/ote_sdk/tests/entities/test_color.py, ote_sdk/ote_sdk/tests/entities/test_label.py, ote_sdk/ote_sdk/tests/entities/test_resultset.py, ote_sdk/ote_sdk/tests/entities/test_scored_label.py, ote_sdk/ote_sdk/tests/entities/test_task_environment.py, ote_sdk/ote_sdk/tests/test_helpers.py
Test list:
ote_sdk/ote_sdk/tests/entities/test_color.py
ote_sdk/ote_sdk/tests/entities/test_label.py
ote_sdk/ote_sdk/tests/entities/test_resultset.py
ote_sdk/ote_sdk/tests/entities/test_scored_label.py
ote_sdk/ote_sdk/tests/entities/test_task_environment.py
Task: CVS-66077
=> OTE_SDK. Increase code coverage.
